# scoring parameters
max_time_per_run_s: 10000.0

# Threshold limit for scoring server to consider that robot is near checkpoint. (metres)
local_thres : 0.35

# detour_checkpoints corresponding to each valid checkpoint. 
detour_checkpoint : 
  - (0, 0, 0)  # ignore this row - the first task checkpoint has no prior detour.
  - (1.5, 2.5, 0) # detour before 2nd task checkpoint
  - (1.5, 2.5, 0) # detour before 3rd task checkpoint

# valid checkpoints in order 
valid_checkpoints : 
  - (0.5, 4.5, 0) # first task checkpoint, this is sent in the start_run ReportingService API
  - (1.5, 4.5, 0) # second task checkpoint
  - (2.5, 4.5, 0) # end goal

# targets {<checkpoint_no> : {id : <checkpoint_no>, situation:<"hostage"/"suspect"/"none">}}
targets:
  1:
    id: 1
    situation : hostage
    audio_path : "/home/yawcz/Documents/plswork/til-23-finals-public/sim_data/orgteam1_vs_orgteam2/valid_checkpoint_1/FoF.zip"
    correct_audio : audio1_teamName One_member2 
    digit_audio_path : "/home/yawcz/Documents/plswork/til-23-finals-public/sim_data/orgteam1_vs_orgteam2/valid_checkpoint_1/Digits.zip"
    digits : (2,2)
  
  2:
    id: 2
    situation : hostage
    audio_path : "/home/yawcz/Documents/plswork/til-23-finals-public/sim_data/orgteam1_vs_orgteam2/valid_checkpoint_1/FoF.zip"
    correct_audio : audio1_teamName One_member2
    digit_audio_path : "/home/yawcz/Documents/plswork/til-23-finals-public/sim_data/orgteam1_vs_orgteam2/valid_checkpoint_1/Digits.zip"
    digits : (3,1)
  
  3:
    id: 3
    situation : hostage
    audio_path : "/home/yawcz/Documents/plswork/til-23-finals-public/sim_data/orgteam1_vs_orgteam2/valid_checkpoint_1/FoF.zip"
    correct_audio : audio1_teamName One_member2
    digit_audio_path : "/home/yawcz/Documents/plswork/til-23-finals-public/sim_data/orgteam1_vs_orgteam2/valid_checkpoint_1/Digits.zip"
    digits : (2,2)

  4:
    id: 4
    situation : hostage
    audio_path : "/home/yawcz/Documents/plswork/til-23-finals-public/sim_data/orgteam1_vs_orgteam2/valid_checkpoint_1/FoF.zip"
    correct_audio : audio1_teamName One_member2
    digit_audio_path : "/home/yawcz/Documents/plswork/til-23-finals-public/sim_data/orgteam1_vs_orgteam2/valid_checkpoint_1/Digits.zip"
    digits : (2,2)
