# logging
log_level: 'warn'

# network
host: '0.0.0.0'
port: 5566

# map
#map_file: '/home/nicholas/code/til-23-finals/data/maps/map_empty_1cm.png'
#map_file: "/home/nicholas/code/til-23-finals/data/maps/map_simple_5x2.png"
map_file: "/home/yawcz/Documents/plswork/til-23-finals-public/sim_data/map_template_3x5_sess3.png"
#map_file: "/home/nicholas/code/til-23-finals/data/maps/map_simple_5x2.png"

# Specify what image the virtual robot should return when using its "camera"
image_file: "/home/yawcz/Documents/plswork/til-23-finals-public/imgs/robot_photo_2023-06-15_11-49-39.jpg"

map_scale: 0.01  # by default, set to 0.01. Ratio of real world units (metres) to one pixel.

# display
robot_radius: 10 

# simulation
start_pose:
  x: 0.5
  y: 0.5
  z: 90
use_noisy_pose: true  # set to true to simulate noisy robot poses.
robot_phy_length: 0.32
position_noise_stddev: 0.35

# localization proxy
proxy_real_robot: false  # if this is true, use_noisy_pose should be false.
proxy_host: '169.254.2.221'  # if using simulator to visualize the REAL robot, point this to the localization server.
proxy_port: 5567  # port number of the localization server.
